### ISSUE TITLE
Optimizer can't find good solutions for some samples

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/grossMethane#18]
As noted in the just-closed #14 , right now the optimizer fits total methane (_m_) well, but for a subset can't replicate labeled methane (_n_). These samples share some characteristics:

![193429400-f58d1569-f0b2-48ce-8563-3528130116a8](https://user-images.githubusercontent.com/1956468/193642977-bc150c62-aed1-4a40-beb3-8f1cd58ff1f0.png)

...such as high initial 12CH4 and 13CH4 and crucially—it seems like—AP that doesn't drop very fast or at all. 

The big question, I think: what next. Do we
* Use this as an interesting/instructive model failure? 
* Test what value(s) of P_FRAC and/or K_FRAC would allow the solver to find reasonable fits for these samples? 
* Let those fractionation constants vary for _all_ samples?

**Comment by bpbond** [comment]
Also, it seems like `optim` can't find good solutions if the numerical values are very small, so we ended up changing from ml/day to µl/day:

https://github.com/COMPASS-DOE/grossMethane/blob/8bbfc1bfde157a63b0cb1aad00e7cf3842768e30/not-a-toy.R#L57-L58

This needs to be documented.

**Comment by kendalynnm** [comment]
Possible issue with gradient vs line function?

https://stat.ethz.ch/pipermail/r-help/2007-February/126209.html

https://stackoverflow.com/questions/11387330/errors-when-attempting-constrained-optimisation-using-optim

$convergence
[1] 52

$message
[1] "ERROR: ABNORMAL_TERMINATION_IN_LNSRCH"

![image](https://user-images.githubusercontent.com/89651444/202567930-c5a064fe-7ba0-4c51-8e60-3da7915dd8a1.png)

**Comment by bpbond** [comment]
"You can try with other optimizers (complete list on the [optimization task view](http://cran.r-project.org/web/views/Optimization.html)), until you find one for which the optimization converges."

Let's discuss.

**Comment by bpbond** [comment]
Seems like this is now occurring for _lots_ of samples.

**Comment by kendalynnm** [comment]
> Seems like this is now occurring for _lots_ of samples.

Hmm...I'm getting the same results after pulling the most recent versions. There are many samples with good fits that generate the error message, is that what you reference here?

**Comment by bpbond** [comment]
Yes, that's what I'm seeing too. I agree, though—the fits are good.

**Comment by kendalynnm** [comment]
This issue was resolved by correctly implementing the cost function, see PoolDilutionR ?pdr_cost()
