### ISSUE TITLE
source methane signature

### ISSUE THREAD

**Issue by kendalynnm** [COMPASS-DOE/grossMethane#23]
Option to saturate lab samples to measure the natural 13C signature of methane

pros:
interesting for determining the dominant methane production pathway
useful for interpreting gross flux data
proof that methane production is possible in all samples in appropriate conditions
not a big time investment

cons: still a time investment

Samples are currently oven-dried and hanging out in my office

**Comment by bpbond** [comment]
Could this credibly be done after oven drying? I guess you wouldn't be raising the idea if not?

**Comment by kendalynnm** [comment]
> Could this credibly be done after oven drying? I guess you wouldn't be raising the idea if not?

Assuming all the methanogens didn't die, yes. The oven was only 65C, but not sure how heat and drought tolerant this group is.
