### ISSUE TITLE
T minus 1 month to AGU

### ISSUE THREAD

**Issue by kendalynnm** [COMPASS-DOE/grossMethane#25]
Highest priority -> poster
- [x] cost function
- [x] figures
- [x] take home message

2023 incubation v2
- [ ] moisture variation vs temperature variation
- [ ] UMD affiliation

paired methane paper
BK methane data, early December

**Comment by kendalynnm** [comment]
poster draft, images and code from Rmarkdown, email a powerpoint back and forth

**Comment by kendalynnm** [comment]
R Package -> Poster vs Manuscript ?
Two sensitivity analyses:
1) Starting P value
2) Dropping one timestep

**Comment by kendalynnm** [comment]
@bpbond
Request for a graph showing different values of P and k as optim() optimizes the solution. Please let me know if I can assist.

**Comment by bpbond** [comment]
I spend a while playing with possibilities. A P-versus-k plot isn't very satisfactory but here's an alternative:

![sample2](https://user-images.githubusercontent.com/1956468/203150738-51983c4b-70a2-4e82-bdd6-4e0e47788bb4.png)

**Comment by bpbond** [comment]
Visualizing the various resulting models:

![sample2_fits](https://user-images.githubusercontent.com/1956468/203151971-2cf0d1e1-c605-4aba-86d8-a48ade7c4d1f.png)

**Comment by kendalynnm** [comment]
Nice! I'm leaning towards version two, although both are very cool!

**Comment by bpbond** [comment]
It's a lot more visually interesting, agreed. I'll add this to your existing Rmd file for the six highlight samples?

**Comment by kendalynnm** [comment]
> It's a lot more visually interesting, agreed. I'll add this to your existing Rmd file for the six highlight samples?

Ideal, thank you!

**Comment by kendalynnm** [comment]
> > It's a lot more visually interesting, agreed. I'll add this to your existing Rmd file for the six highlight samples?
> 
> Ideal, thank you!

Just checking to see if this is ready? Absolutely no worries if not, just working on the poster a bit this morning and got curious.

**Comment by bpbond** [comment]
https://github.com/COMPASS-DOE/grossMethane/pull/29

😄
