### ISSUE TITLE
trial 2 data for AGU abstract

### ISSUE THREAD

**Issue by kendalynnm** [COMPASS-DOE/grossMethane#7]
Hi @bpbond,
The branch "semi-automated processing" has all three Picarro csv files with the necessary meta-data for processing in the 'toy' model. Let me know if you have any questions about column ids - and warning that the default output column names are not very R friendly.
Thank you!
Kendal

**Comment by bpbond** [comment]
Hi @kendalynnm -

What do "HP" and "HR" stand for in the column names?

Ignoring units for the moment, does this look right?

This field in toy code... | ...corresponds to this column in Picarro data
---------------------- | ------------------
cal12CH4ml | 12CO2 Mean
cal13CH4ml | 13CO2 Mean

**Comment by bpbond** [comment]
Next question. All samples have a second T4 observation that's, well, weird; and sample 10 has a wacky T5 13C number:
```
> filter(incdat, id==10)
# A tibble: 7 × 8
# Groups:   id [1]
  Timestamp           id    round   vol mean12CO2 mean13CO2 notes                                        Elapsed        
  <dttm>              <fct> <chr> <dbl>     <dbl>     <dbl> <chr>                                        <drtn>         
1 2022-07-21 16:09:00 10    T0       10      378.      4.32 NA                                           0.00000000 days
2 2022-07-21 17:50:00 10    T1       10     1328.     15.1  NA                                           0.07013889 days
3 2022-07-21 20:39:00 10    T2       10     2290.     25.8  NA                                           0.18750000 days
4 2022-07-21 22:33:00 10    T3       10     3425.     38.7  something went deeply wrong with this sample 0.26666667 days
5 2022-07-22 20:13:00 10    T4       10     4141.     46.8  zero air added                               1.16944444 days
6 2022-07-22 20:23:00 10    T4        2      885.      9.76 zero air added                               1.17638889 days
7 2022-07-22 22:04:00 10    T5       10     4108.    767.   no zero air added                            1.24652778 days
```
![t4](https://user-images.githubusercontent.com/1956468/181213700-f4a99efc-b586-4e10-8468-e64d5e2204a1.png)

Drop these data? Or something else?

**Comment by bpbond** [comment]
> samples were in the fridge overnight between T3 and T4

Hmmm.

**Comment by bpbond** [comment]
Dropping T4 vol=2 data and removing that one very high T5 13CO2:

![over_time](https://user-images.githubusercontent.com/1956468/181228717-4f099bd0-63fd-42b1-8670-5c6440e91d58.png)

Uh oh...that can't be right.

**Comment by bpbond** [comment]
Opening a PR for you to play with. Initial results:

![ap_pred](https://user-images.githubusercontent.com/1956468/181229276-aee0ce12-bd4d-4279-841f-ac21e60eb98c.png)

```
   id        P       k
   <chr> <dbl>   <dbl>
 1 1     0.433 -0.0262
 2 2     6.80  -0.378 
 3 3     2.66  -0.187 
 4 4     3.91  -0.254 
 5 5     5.22  -0.304 
 6 6     4.48  -0.250 
 7 7     2.09  -0.159 
 8 8     4.89  -0.324 
 9 9     5.35  -0.408 
10 10    6.27  -0.337 
```
